//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPlay.Web.SuzyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SuzyService.SuzyServiceSoap")]
    public interface SuzyServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateStats(int nUserId, int nGoldDelta, int nIngredientValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStats", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateStatsAsync(int nUserId, int nGoldDelta, int nIngredientValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatsV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateStatsV2(int nUserId, int nGoldDelta, int nIngredientValue, int nHellKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatsV2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateStatsV2Async(int nUserId, int nGoldDelta, int nIngredientValue, int nHellKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRanking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetRanking(string sGTokenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRanking", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetRankingAsync(string sGTokenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateGoldForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateGoldForUser(string sGTokenId, int nGoldAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateGoldForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateGoldForUserAsync(string sGTokenId, int nGoldAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Sync(int nUserId, string sJSyncInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sync", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncAsync(int nUserId, string sJSyncInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncV2(int nUserId, string sJSyncInfoV2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncV2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncV2Async(int nUserId, string sJSyncInfoV2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHellLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateHellLevel(int nUserId, int nLevel, int nStar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHellLevel", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateHellLevelAsync(int nUserId, int nLevel, int nStar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateLevel(int nUserId, int nLevel, int nStar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLevel", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateLevelAsync(int nUserId, int nLevel, int nStar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveUserId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RetrieveUserId(string sSocialId, int nDefaultSocialPlatform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RetrieveUserIdAsync(string sSocialId, int nDefaultSocialPlatform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserIdAndLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CreateUserIdAndLink(string sSocialId, string sGTokenId, int nDefaultSocialPlatform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserIdAndLink", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CreateUserIdAndLinkAsync(string sSocialId, string sGTokenId, int nDefaultSocialPlatform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGTokenRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.SuzyService.GTokenRecord[] GetGTokenRecords(System.DateTime Start, System.DateTime End);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGTokenRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.SuzyService.GTokenRecord[]> GetGTokenRecordsAsync(System.DateTime Start, System.DateTime End);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GTokenRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gTokenIdField;
        
        private int goldField;
        
        private System.DateTime recordDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GTokenId {
            get {
                return this.gTokenIdField;
            }
            set {
                this.gTokenIdField = value;
                this.RaisePropertyChanged("GTokenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Gold {
            get {
                return this.goldField;
            }
            set {
                this.goldField = value;
                this.RaisePropertyChanged("Gold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime RecordDate {
            get {
                return this.recordDateField;
            }
            set {
                this.recordDateField = value;
                this.RaisePropertyChanged("RecordDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SuzyServiceSoapChannel : GoPlay.Web.SuzyService.SuzyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuzyServiceSoapClient : System.ServiceModel.ClientBase<GoPlay.Web.SuzyService.SuzyServiceSoap>, GoPlay.Web.SuzyService.SuzyServiceSoap {
        
        public SuzyServiceSoapClient() {
        }
        
        public SuzyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuzyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuzyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuzyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UpdateStats(int nUserId, int nGoldDelta, int nIngredientValue) {
            return base.Channel.UpdateStats(nUserId, nGoldDelta, nIngredientValue);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStatsAsync(int nUserId, int nGoldDelta, int nIngredientValue) {
            return base.Channel.UpdateStatsAsync(nUserId, nGoldDelta, nIngredientValue);
        }
        
        public string UpdateStatsV2(int nUserId, int nGoldDelta, int nIngredientValue, int nHellKey) {
            return base.Channel.UpdateStatsV2(nUserId, nGoldDelta, nIngredientValue, nHellKey);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStatsV2Async(int nUserId, int nGoldDelta, int nIngredientValue, int nHellKey) {
            return base.Channel.UpdateStatsV2Async(nUserId, nGoldDelta, nIngredientValue, nHellKey);
        }
        
        public int GetRanking(string sGTokenId) {
            return base.Channel.GetRanking(sGTokenId);
        }
        
        public System.Threading.Tasks.Task<int> GetRankingAsync(string sGTokenId) {
            return base.Channel.GetRankingAsync(sGTokenId);
        }
        
        public bool UpdateGoldForUser(string sGTokenId, int nGoldAmount) {
            return base.Channel.UpdateGoldForUser(sGTokenId, nGoldAmount);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateGoldForUserAsync(string sGTokenId, int nGoldAmount) {
            return base.Channel.UpdateGoldForUserAsync(sGTokenId, nGoldAmount);
        }
        
        public string Sync(int nUserId, string sJSyncInfo) {
            return base.Channel.Sync(nUserId, sJSyncInfo);
        }
        
        public System.Threading.Tasks.Task<string> SyncAsync(int nUserId, string sJSyncInfo) {
            return base.Channel.SyncAsync(nUserId, sJSyncInfo);
        }
        
        public string SyncV2(int nUserId, string sJSyncInfoV2) {
            return base.Channel.SyncV2(nUserId, sJSyncInfoV2);
        }
        
        public System.Threading.Tasks.Task<string> SyncV2Async(int nUserId, string sJSyncInfoV2) {
            return base.Channel.SyncV2Async(nUserId, sJSyncInfoV2);
        }
        
        public bool UpdateHellLevel(int nUserId, int nLevel, int nStar) {
            return base.Channel.UpdateHellLevel(nUserId, nLevel, nStar);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateHellLevelAsync(int nUserId, int nLevel, int nStar) {
            return base.Channel.UpdateHellLevelAsync(nUserId, nLevel, nStar);
        }
        
        public bool UpdateLevel(int nUserId, int nLevel, int nStar) {
            return base.Channel.UpdateLevel(nUserId, nLevel, nStar);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateLevelAsync(int nUserId, int nLevel, int nStar) {
            return base.Channel.UpdateLevelAsync(nUserId, nLevel, nStar);
        }
        
        public int RetrieveUserId(string sSocialId, int nDefaultSocialPlatform) {
            return base.Channel.RetrieveUserId(sSocialId, nDefaultSocialPlatform);
        }
        
        public System.Threading.Tasks.Task<int> RetrieveUserIdAsync(string sSocialId, int nDefaultSocialPlatform) {
            return base.Channel.RetrieveUserIdAsync(sSocialId, nDefaultSocialPlatform);
        }
        
        public int CreateUserIdAndLink(string sSocialId, string sGTokenId, int nDefaultSocialPlatform) {
            return base.Channel.CreateUserIdAndLink(sSocialId, sGTokenId, nDefaultSocialPlatform);
        }
        
        public System.Threading.Tasks.Task<int> CreateUserIdAndLinkAsync(string sSocialId, string sGTokenId, int nDefaultSocialPlatform) {
            return base.Channel.CreateUserIdAndLinkAsync(sSocialId, sGTokenId, nDefaultSocialPlatform);
        }
        
        public GoPlay.Web.SuzyService.GTokenRecord[] GetGTokenRecords(System.DateTime Start, System.DateTime End) {
            return base.Channel.GetGTokenRecords(Start, End);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.SuzyService.GTokenRecord[]> GetGTokenRecordsAsync(System.DateTime Start, System.DateTime End) {
            return base.Channel.GetGTokenRecordsAsync(Start, End);
        }
    }
}
