//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPlay.Web.MineManiaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MineManiaService.MMWSSoap")]
    public interface MMWSSoap {
        
        // CODEGEN: Parameter 'UpdateProgesssResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="UpdateProgesssResult")]
        GoPlay.Web.MineManiaService.UpdateProgressResponse UpdateProgress(GoPlay.Web.MineManiaService.UpdateProgressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProgress", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.UpdateProgressResponse> UpdateProgressAsync(GoPlay.Web.MineManiaService.UpdateProgressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatsDelta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.MineManiaService.PlayerStats UpdateStatsDelta(string sFBId, GoPlay.Web.MineManiaService.StatsDelta delta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatsDelta", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.PlayerStats> UpdateStatsDeltaAsync(string sFBId, GoPlay.Web.MineManiaService.StatsDelta delta);
        
        // CODEGEN: Parameter 'SyncAll' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncAllWithMLM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SyncAll")]
        GoPlay.Web.MineManiaService.SyncAllWithMLMResponse SyncAllWithMLM(GoPlay.Web.MineManiaService.SyncAllWithMLMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncAllWithMLM", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.SyncAllWithMLMResponse> SyncAllWithMLMAsync(GoPlay.Web.MineManiaService.SyncAllWithMLMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.MineManiaService.GTokenRecord[] GetRecord(System.DateTime Start, System.DateTime End);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.GTokenRecord[]> GetRecordAsync(System.DateTime Start, System.DateTime End);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateGoldForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateGoldForUser(string sGTokenId, int nGoldAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateGoldForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateGoldForUserAsync(string sGTokenId, int nGoldAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHighestLevelForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetHighestLevelForUser(string sGTokenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHighestLevelForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetHighestLevelForUserAsync(string sGTokenId);
        
        // CODEGEN: Parameter 'SyncAll' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SyncAll")]
        GoPlay.Web.MineManiaService.SyncAllResponse SyncAll(GoPlay.Web.MineManiaService.SyncAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncAll", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.SyncAllResponse> SyncAllAsync(GoPlay.Web.MineManiaService.SyncAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRankings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.MineManiaService.Score[] GetRankings(string[] sFriendIds, string sMyFBId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRankings", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.Score[]> GetRankingsAsync(string[] sFriendIds, string sMyFBId, int nLevel);
        
        // CODEGEN: Parameter 'Usage' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsNewDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Usage")]
        GoPlay.Web.MineManiaService.IsNewDayResponse IsNewDay(GoPlay.Web.MineManiaService.IsNewDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsNewDay", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.IsNewDayResponse> IsNewDayAsync(GoPlay.Web.MineManiaService.IsNewDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGiftRedemptionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.MineManiaService.GiftRedemptionInfo GetGiftRedemptionInfo(string sMyFBId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGiftRedemptionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.GiftRedemptionInfo> GetGiftRedemptionInfoAsync(string sMyFBId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetGiftRedemptionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SetGiftRedemptionInfo(string sMyFBId, int nRedeemCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetGiftRedemptionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task SetGiftRedemptionInfoAsync(string sMyFBId, int nRedeemCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetTicketInfo(string sMyFBId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetTicketInfoAsync(string sMyFBId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTicketInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddTicketInfo(string sMyFBId, int nLevel, string[] FbIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTicketInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddTicketInfoAsync(string sMyFBId, int nLevel, string[] FbIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnlockLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UnlockLevel(string sMyFBId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnlockLevel", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UnlockLevelAsync(string sMyFBId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2GetUserId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.MineManiaService.UserInfo V2GetUserId(string SocialId, string GTokenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2GetUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.UserInfo> V2GetUserIdAsync(string SocialId, string GTokenId);
        
        // CODEGEN: Parameter 'UpdateProgesssResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2UpdateProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="UpdateProgesssResult")]
        GoPlay.Web.MineManiaService.V2UpdateProgressResponse V2UpdateProgress(GoPlay.Web.MineManiaService.V2UpdateProgressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2UpdateProgress", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2UpdateProgressResponse> V2UpdateProgressAsync(GoPlay.Web.MineManiaService.V2UpdateProgressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2UpdateStatsDelta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.MineManiaService.PlayerStats V2UpdateStatsDelta(int nUserId, GoPlay.Web.MineManiaService.StatsDelta delta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2UpdateStatsDelta", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.PlayerStats> V2UpdateStatsDeltaAsync(int nUserId, GoPlay.Web.MineManiaService.StatsDelta delta);
        
        // CODEGEN: Parameter 'SyncAll' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2SyncAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SyncAll")]
        GoPlay.Web.MineManiaService.V2SyncAllResponse V2SyncAll(GoPlay.Web.MineManiaService.V2SyncAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2SyncAll", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2SyncAllResponse> V2SyncAllAsync(GoPlay.Web.MineManiaService.V2SyncAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2GetRankings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.MineManiaService.Score[] V2GetRankings(string[] sFriendIds, int nMyUserId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2GetRankings", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.Score[]> V2GetRankingsAsync(string[] sFriendIds, int nMyUserId, int nLevel);
        
        // CODEGEN: Parameter 'Usage' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2IsNewDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Usage")]
        GoPlay.Web.MineManiaService.V2IsNewDayResponse V2IsNewDay(GoPlay.Web.MineManiaService.V2IsNewDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2IsNewDay", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2IsNewDayResponse> V2IsNewDayAsync(GoPlay.Web.MineManiaService.V2IsNewDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2GetGiftRedemptionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GoPlay.Web.MineManiaService.GiftRedemptionInfo V2GetGiftRedemptionInfo(string sMyFBId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2GetGiftRedemptionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.GiftRedemptionInfo> V2GetGiftRedemptionInfoAsync(string sMyFBId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2SetGiftRedemptionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void V2SetGiftRedemptionInfo(string sMyFBId, int nRedeemCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2SetGiftRedemptionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task V2SetGiftRedemptionInfoAsync(string sMyFBId, int nRedeemCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2GetTicketInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] V2GetTicketInfo(string sMyFBId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2GetTicketInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> V2GetTicketInfoAsync(string sMyFBId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2AddTicketInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int V2AddTicketInfo(string sMyFBId, int nLevel, string[] FbIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2AddTicketInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> V2AddTicketInfoAsync(string sMyFBId, int nLevel, string[] FbIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2UnlockLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool V2UnlockLevel(int nUserId, int nLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/V2UnlockLevel", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> V2UnlockLevelAsync(int nUserId, int nLevel);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Progress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int levelField;
        
        private bool passedField;
        
        private int scoreField;
        
        private int starsField;
        
        private int goldDeltaField;
        
        private int[] sPsDeltaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Passed {
            get {
                return this.passedField;
            }
            set {
                this.passedField = value;
                this.RaisePropertyChanged("Passed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("Score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
                this.RaisePropertyChanged("Stars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int GoldDelta {
            get {
                return this.goldDeltaField;
            }
            set {
                this.goldDeltaField = value;
                this.RaisePropertyChanged("GoldDelta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public int[] SPsDelta {
            get {
                return this.sPsDeltaField;
            }
            set {
                this.sPsDeltaField = value;
                this.RaisePropertyChanged("SPsDelta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncInfoV2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIdField;
        
        private LevelScore[] levelScoresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public LevelScore[] LevelScores {
            get {
                return this.levelScoresField;
            }
            set {
                this.levelScoresField = value;
                this.RaisePropertyChanged("LevelScores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LevelScore : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int levelField;
        
        private long scoreField;
        
        private int starsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("Score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
                this.RaisePropertyChanged("Stars");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GiftRedemptionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int redeemedCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RedeemedCount {
            get {
                return this.redeemedCountField;
            }
            set {
                this.redeemedCountField = value;
                this.RaisePropertyChanged("RedeemedCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsageResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isNewDayField;
        
        private int cumulativeDaysPlayedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsNewDay {
            get {
                return this.isNewDayField;
            }
            set {
                this.isNewDayField = value;
                this.RaisePropertyChanged("IsNewDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CumulativeDaysPlayed {
            get {
                return this.cumulativeDaysPlayedField;
            }
            set {
                this.cumulativeDaysPlayedField = value;
                this.RaisePropertyChanged("CumulativeDaysPlayed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Score : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string friendIdField;
        
        private int rankField;
        
        private long topScoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FriendId {
            get {
                return this.friendIdField;
            }
            set {
                this.friendIdField = value;
                this.RaisePropertyChanged("FriendId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("Rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long TopScore {
            get {
                return this.topScoreField;
            }
            set {
                this.topScoreField = value;
                this.RaisePropertyChanged("TopScore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GTokenRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gTokenIdField;
        
        private int goldField;
        
        private System.DateTime recordDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GTokenId {
            get {
                return this.gTokenIdField;
            }
            set {
                this.gTokenIdField = value;
                this.RaisePropertyChanged("GTokenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Gold {
            get {
                return this.goldField;
            }
            set {
                this.goldField = value;
                this.RaisePropertyChanged("Gold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime RecordDate {
            get {
                return this.recordDateField;
            }
            set {
                this.recordDateField = value;
                this.RaisePropertyChanged("RecordDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LevelScore[] levelScoresField;
        
        private PlayerStats playerStatsField;
        
        private bool isGetGoldFromGTokenField;
        
        private int goldAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LevelScore[] LevelScores {
            get {
                return this.levelScoresField;
            }
            set {
                this.levelScoresField = value;
                this.RaisePropertyChanged("LevelScores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PlayerStats PlayerStats {
            get {
                return this.playerStatsField;
            }
            set {
                this.playerStatsField = value;
                this.RaisePropertyChanged("PlayerStats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsGetGoldFromGToken {
            get {
                return this.isGetGoldFromGTokenField;
            }
            set {
                this.isGetGoldFromGTokenField = value;
                this.RaisePropertyChanged("IsGetGoldFromGToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GoldAmount {
            get {
                return this.goldAmountField;
            }
            set {
                this.goldAmountField = value;
                this.RaisePropertyChanged("GoldAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PlayerStats : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIdField;
        
        private int goldField;
        
        private int[] sPsField;
        
        private int highestPlayedLevelField;
        
        private int highestUnlockedLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Gold {
            get {
                return this.goldField;
            }
            set {
                this.goldField = value;
                this.RaisePropertyChanged("Gold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public int[] SPs {
            get {
                return this.sPsField;
            }
            set {
                this.sPsField = value;
                this.RaisePropertyChanged("SPs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int HighestPlayedLevel {
            get {
                return this.highestPlayedLevelField;
            }
            set {
                this.highestPlayedLevelField = value;
                this.RaisePropertyChanged("HighestPlayedLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int HighestUnlockedLevel {
            get {
                return this.highestUnlockedLevelField;
            }
            set {
                this.highestUnlockedLevelField = value;
                this.RaisePropertyChanged("HighestUnlockedLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fbIdField;
        
        private LevelScore[] levelScoresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FbId {
            get {
                return this.fbIdField;
            }
            set {
                this.fbIdField = value;
                this.RaisePropertyChanged("FbId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public LevelScore[] LevelScores {
            get {
                return this.levelScoresField;
            }
            set {
                this.levelScoresField = value;
                this.RaisePropertyChanged("LevelScores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StatsDelta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int goldDeltaField;
        
        private int[] sPsDeltaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GoldDelta {
            get {
                return this.goldDeltaField;
            }
            set {
                this.goldDeltaField = value;
                this.RaisePropertyChanged("GoldDelta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public int[] SPsDelta {
            get {
                return this.sPsDeltaField;
            }
            set {
                this.sPsDeltaField = value;
                this.RaisePropertyChanged("SPsDelta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProgressResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool passedField;
        
        private int levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Passed {
            get {
                return this.passedField;
            }
            set {
                this.passedField = value;
                this.RaisePropertyChanged("Passed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateProgress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateProgressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sFBId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GoPlay.Web.MineManiaService.Progress info;
        
        public UpdateProgressRequest() {
        }
        
        public UpdateProgressRequest(string sFBId, GoPlay.Web.MineManiaService.Progress info) {
            this.sFBId = sFBId;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateProgressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateProgressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GoPlay.Web.MineManiaService.UpdateProgressResult UpdateProgesssResult;
        
        public UpdateProgressResponse() {
        }
        
        public UpdateProgressResponse(GoPlay.Web.MineManiaService.UpdateProgressResult UpdateProgesssResult) {
            this.UpdateProgesssResult = UpdateProgesssResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncAllWithMLM", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncAllWithMLMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sGTokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GoPlay.Web.MineManiaService.SyncInfo info;
        
        public SyncAllWithMLMRequest() {
        }
        
        public SyncAllWithMLMRequest(string sGTokenId, GoPlay.Web.MineManiaService.SyncInfo info) {
            this.sGTokenId = sGTokenId;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncAllWithMLMResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncAllWithMLMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GoPlay.Web.MineManiaService.SyncResult SyncAll;
        
        public SyncAllWithMLMResponse() {
        }
        
        public SyncAllWithMLMResponse(GoPlay.Web.MineManiaService.SyncResult SyncAll) {
            this.SyncAll = SyncAll;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncAll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GoPlay.Web.MineManiaService.SyncInfo info;
        
        public SyncAllRequest() {
        }
        
        public SyncAllRequest(GoPlay.Web.MineManiaService.SyncInfo info) {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncAllResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GoPlay.Web.MineManiaService.SyncResult SyncAll;
        
        public SyncAllResponse() {
        }
        
        public SyncAllResponse(GoPlay.Web.MineManiaService.SyncResult SyncAll) {
            this.SyncAll = SyncAll;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsNewDay", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsNewDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sMyFBId;
        
        public IsNewDayRequest() {
        }
        
        public IsNewDayRequest(string sMyFBId) {
            this.sMyFBId = sMyFBId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsNewDayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsNewDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GoPlay.Web.MineManiaService.UsageResult Usage;
        
        public IsNewDayResponse() {
        }
        
        public IsNewDayResponse(GoPlay.Web.MineManiaService.UsageResult Usage) {
            this.Usage = Usage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="V2UpdateProgress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class V2UpdateProgressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int nUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GoPlay.Web.MineManiaService.Progress info;
        
        public V2UpdateProgressRequest() {
        }
        
        public V2UpdateProgressRequest(int nUserId, GoPlay.Web.MineManiaService.Progress info) {
            this.nUserId = nUserId;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="V2UpdateProgressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class V2UpdateProgressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GoPlay.Web.MineManiaService.UpdateProgressResult UpdateProgesssResult;
        
        public V2UpdateProgressResponse() {
        }
        
        public V2UpdateProgressResponse(GoPlay.Web.MineManiaService.UpdateProgressResult UpdateProgesssResult) {
            this.UpdateProgesssResult = UpdateProgesssResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="V2SyncAll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class V2SyncAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GoPlay.Web.MineManiaService.SyncInfoV2 info;
        
        public V2SyncAllRequest() {
        }
        
        public V2SyncAllRequest(GoPlay.Web.MineManiaService.SyncInfoV2 info) {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="V2SyncAllResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class V2SyncAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GoPlay.Web.MineManiaService.SyncResult SyncAll;
        
        public V2SyncAllResponse() {
        }
        
        public V2SyncAllResponse(GoPlay.Web.MineManiaService.SyncResult SyncAll) {
            this.SyncAll = SyncAll;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="V2IsNewDay", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class V2IsNewDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int nUserId;
        
        public V2IsNewDayRequest() {
        }
        
        public V2IsNewDayRequest(int nUserId) {
            this.nUserId = nUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="V2IsNewDayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class V2IsNewDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GoPlay.Web.MineManiaService.UsageResult Usage;
        
        public V2IsNewDayResponse() {
        }
        
        public V2IsNewDayResponse(GoPlay.Web.MineManiaService.UsageResult Usage) {
            this.Usage = Usage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MMWSSoapChannel : GoPlay.Web.MineManiaService.MMWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MMWSSoapClient : System.ServiceModel.ClientBase<GoPlay.Web.MineManiaService.MMWSSoap>, GoPlay.Web.MineManiaService.MMWSSoap {
        
        public MMWSSoapClient() {
        }
        
        public MMWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MMWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MMWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MMWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoPlay.Web.MineManiaService.UpdateProgressResponse GoPlay.Web.MineManiaService.MMWSSoap.UpdateProgress(GoPlay.Web.MineManiaService.UpdateProgressRequest request) {
            return base.Channel.UpdateProgress(request);
        }
        
        public GoPlay.Web.MineManiaService.UpdateProgressResult UpdateProgress(string sFBId, GoPlay.Web.MineManiaService.Progress info) {
            GoPlay.Web.MineManiaService.UpdateProgressRequest inValue = new GoPlay.Web.MineManiaService.UpdateProgressRequest();
            inValue.sFBId = sFBId;
            inValue.info = info;
            GoPlay.Web.MineManiaService.UpdateProgressResponse retVal = ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).UpdateProgress(inValue);
            return retVal.UpdateProgesssResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.UpdateProgressResponse> GoPlay.Web.MineManiaService.MMWSSoap.UpdateProgressAsync(GoPlay.Web.MineManiaService.UpdateProgressRequest request) {
            return base.Channel.UpdateProgressAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.UpdateProgressResponse> UpdateProgressAsync(string sFBId, GoPlay.Web.MineManiaService.Progress info) {
            GoPlay.Web.MineManiaService.UpdateProgressRequest inValue = new GoPlay.Web.MineManiaService.UpdateProgressRequest();
            inValue.sFBId = sFBId;
            inValue.info = info;
            return ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).UpdateProgressAsync(inValue);
        }
        
        public GoPlay.Web.MineManiaService.PlayerStats UpdateStatsDelta(string sFBId, GoPlay.Web.MineManiaService.StatsDelta delta) {
            return base.Channel.UpdateStatsDelta(sFBId, delta);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.PlayerStats> UpdateStatsDeltaAsync(string sFBId, GoPlay.Web.MineManiaService.StatsDelta delta) {
            return base.Channel.UpdateStatsDeltaAsync(sFBId, delta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoPlay.Web.MineManiaService.SyncAllWithMLMResponse GoPlay.Web.MineManiaService.MMWSSoap.SyncAllWithMLM(GoPlay.Web.MineManiaService.SyncAllWithMLMRequest request) {
            return base.Channel.SyncAllWithMLM(request);
        }
        
        public GoPlay.Web.MineManiaService.SyncResult SyncAllWithMLM(string sGTokenId, GoPlay.Web.MineManiaService.SyncInfo info) {
            GoPlay.Web.MineManiaService.SyncAllWithMLMRequest inValue = new GoPlay.Web.MineManiaService.SyncAllWithMLMRequest();
            inValue.sGTokenId = sGTokenId;
            inValue.info = info;
            GoPlay.Web.MineManiaService.SyncAllWithMLMResponse retVal = ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).SyncAllWithMLM(inValue);
            return retVal.SyncAll;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.SyncAllWithMLMResponse> GoPlay.Web.MineManiaService.MMWSSoap.SyncAllWithMLMAsync(GoPlay.Web.MineManiaService.SyncAllWithMLMRequest request) {
            return base.Channel.SyncAllWithMLMAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.SyncAllWithMLMResponse> SyncAllWithMLMAsync(string sGTokenId, GoPlay.Web.MineManiaService.SyncInfo info) {
            GoPlay.Web.MineManiaService.SyncAllWithMLMRequest inValue = new GoPlay.Web.MineManiaService.SyncAllWithMLMRequest();
            inValue.sGTokenId = sGTokenId;
            inValue.info = info;
            return ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).SyncAllWithMLMAsync(inValue);
        }
        
        public GoPlay.Web.MineManiaService.GTokenRecord[] GetRecord(System.DateTime Start, System.DateTime End) {
            return base.Channel.GetRecord(Start, End);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.GTokenRecord[]> GetRecordAsync(System.DateTime Start, System.DateTime End) {
            return base.Channel.GetRecordAsync(Start, End);
        }
        
        public bool UpdateGoldForUser(string sGTokenId, int nGoldAmount) {
            return base.Channel.UpdateGoldForUser(sGTokenId, nGoldAmount);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateGoldForUserAsync(string sGTokenId, int nGoldAmount) {
            return base.Channel.UpdateGoldForUserAsync(sGTokenId, nGoldAmount);
        }
        
        public int GetHighestLevelForUser(string sGTokenId) {
            return base.Channel.GetHighestLevelForUser(sGTokenId);
        }
        
        public System.Threading.Tasks.Task<int> GetHighestLevelForUserAsync(string sGTokenId) {
            return base.Channel.GetHighestLevelForUserAsync(sGTokenId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoPlay.Web.MineManiaService.SyncAllResponse GoPlay.Web.MineManiaService.MMWSSoap.SyncAll(GoPlay.Web.MineManiaService.SyncAllRequest request) {
            return base.Channel.SyncAll(request);
        }
        
        public GoPlay.Web.MineManiaService.SyncResult SyncAll(GoPlay.Web.MineManiaService.SyncInfo info) {
            GoPlay.Web.MineManiaService.SyncAllRequest inValue = new GoPlay.Web.MineManiaService.SyncAllRequest();
            inValue.info = info;
            GoPlay.Web.MineManiaService.SyncAllResponse retVal = ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).SyncAll(inValue);
            return retVal.SyncAll;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.SyncAllResponse> GoPlay.Web.MineManiaService.MMWSSoap.SyncAllAsync(GoPlay.Web.MineManiaService.SyncAllRequest request) {
            return base.Channel.SyncAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.SyncAllResponse> SyncAllAsync(GoPlay.Web.MineManiaService.SyncInfo info) {
            GoPlay.Web.MineManiaService.SyncAllRequest inValue = new GoPlay.Web.MineManiaService.SyncAllRequest();
            inValue.info = info;
            return ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).SyncAllAsync(inValue);
        }
        
        public GoPlay.Web.MineManiaService.Score[] GetRankings(string[] sFriendIds, string sMyFBId, int nLevel) {
            return base.Channel.GetRankings(sFriendIds, sMyFBId, nLevel);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.Score[]> GetRankingsAsync(string[] sFriendIds, string sMyFBId, int nLevel) {
            return base.Channel.GetRankingsAsync(sFriendIds, sMyFBId, nLevel);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoPlay.Web.MineManiaService.IsNewDayResponse GoPlay.Web.MineManiaService.MMWSSoap.IsNewDay(GoPlay.Web.MineManiaService.IsNewDayRequest request) {
            return base.Channel.IsNewDay(request);
        }
        
        public GoPlay.Web.MineManiaService.UsageResult IsNewDay(string sMyFBId) {
            GoPlay.Web.MineManiaService.IsNewDayRequest inValue = new GoPlay.Web.MineManiaService.IsNewDayRequest();
            inValue.sMyFBId = sMyFBId;
            GoPlay.Web.MineManiaService.IsNewDayResponse retVal = ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).IsNewDay(inValue);
            return retVal.Usage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.IsNewDayResponse> GoPlay.Web.MineManiaService.MMWSSoap.IsNewDayAsync(GoPlay.Web.MineManiaService.IsNewDayRequest request) {
            return base.Channel.IsNewDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.IsNewDayResponse> IsNewDayAsync(string sMyFBId) {
            GoPlay.Web.MineManiaService.IsNewDayRequest inValue = new GoPlay.Web.MineManiaService.IsNewDayRequest();
            inValue.sMyFBId = sMyFBId;
            return ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).IsNewDayAsync(inValue);
        }
        
        public GoPlay.Web.MineManiaService.GiftRedemptionInfo GetGiftRedemptionInfo(string sMyFBId) {
            return base.Channel.GetGiftRedemptionInfo(sMyFBId);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.GiftRedemptionInfo> GetGiftRedemptionInfoAsync(string sMyFBId) {
            return base.Channel.GetGiftRedemptionInfoAsync(sMyFBId);
        }
        
        public void SetGiftRedemptionInfo(string sMyFBId, int nRedeemCount) {
            base.Channel.SetGiftRedemptionInfo(sMyFBId, nRedeemCount);
        }
        
        public System.Threading.Tasks.Task SetGiftRedemptionInfoAsync(string sMyFBId, int nRedeemCount) {
            return base.Channel.SetGiftRedemptionInfoAsync(sMyFBId, nRedeemCount);
        }
        
        public string[] GetTicketInfo(string sMyFBId, int nLevel) {
            return base.Channel.GetTicketInfo(sMyFBId, nLevel);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTicketInfoAsync(string sMyFBId, int nLevel) {
            return base.Channel.GetTicketInfoAsync(sMyFBId, nLevel);
        }
        
        public int AddTicketInfo(string sMyFBId, int nLevel, string[] FbIds) {
            return base.Channel.AddTicketInfo(sMyFBId, nLevel, FbIds);
        }
        
        public System.Threading.Tasks.Task<int> AddTicketInfoAsync(string sMyFBId, int nLevel, string[] FbIds) {
            return base.Channel.AddTicketInfoAsync(sMyFBId, nLevel, FbIds);
        }
        
        public bool UnlockLevel(string sMyFBId, int nLevel) {
            return base.Channel.UnlockLevel(sMyFBId, nLevel);
        }
        
        public System.Threading.Tasks.Task<bool> UnlockLevelAsync(string sMyFBId, int nLevel) {
            return base.Channel.UnlockLevelAsync(sMyFBId, nLevel);
        }
        
        public GoPlay.Web.MineManiaService.UserInfo V2GetUserId(string SocialId, string GTokenId) {
            return base.Channel.V2GetUserId(SocialId, GTokenId);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.UserInfo> V2GetUserIdAsync(string SocialId, string GTokenId) {
            return base.Channel.V2GetUserIdAsync(SocialId, GTokenId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoPlay.Web.MineManiaService.V2UpdateProgressResponse GoPlay.Web.MineManiaService.MMWSSoap.V2UpdateProgress(GoPlay.Web.MineManiaService.V2UpdateProgressRequest request) {
            return base.Channel.V2UpdateProgress(request);
        }
        
        public GoPlay.Web.MineManiaService.UpdateProgressResult V2UpdateProgress(int nUserId, GoPlay.Web.MineManiaService.Progress info) {
            GoPlay.Web.MineManiaService.V2UpdateProgressRequest inValue = new GoPlay.Web.MineManiaService.V2UpdateProgressRequest();
            inValue.nUserId = nUserId;
            inValue.info = info;
            GoPlay.Web.MineManiaService.V2UpdateProgressResponse retVal = ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).V2UpdateProgress(inValue);
            return retVal.UpdateProgesssResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2UpdateProgressResponse> GoPlay.Web.MineManiaService.MMWSSoap.V2UpdateProgressAsync(GoPlay.Web.MineManiaService.V2UpdateProgressRequest request) {
            return base.Channel.V2UpdateProgressAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2UpdateProgressResponse> V2UpdateProgressAsync(int nUserId, GoPlay.Web.MineManiaService.Progress info) {
            GoPlay.Web.MineManiaService.V2UpdateProgressRequest inValue = new GoPlay.Web.MineManiaService.V2UpdateProgressRequest();
            inValue.nUserId = nUserId;
            inValue.info = info;
            return ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).V2UpdateProgressAsync(inValue);
        }
        
        public GoPlay.Web.MineManiaService.PlayerStats V2UpdateStatsDelta(int nUserId, GoPlay.Web.MineManiaService.StatsDelta delta) {
            return base.Channel.V2UpdateStatsDelta(nUserId, delta);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.PlayerStats> V2UpdateStatsDeltaAsync(int nUserId, GoPlay.Web.MineManiaService.StatsDelta delta) {
            return base.Channel.V2UpdateStatsDeltaAsync(nUserId, delta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoPlay.Web.MineManiaService.V2SyncAllResponse GoPlay.Web.MineManiaService.MMWSSoap.V2SyncAll(GoPlay.Web.MineManiaService.V2SyncAllRequest request) {
            return base.Channel.V2SyncAll(request);
        }
        
        public GoPlay.Web.MineManiaService.SyncResult V2SyncAll(GoPlay.Web.MineManiaService.SyncInfoV2 info) {
            GoPlay.Web.MineManiaService.V2SyncAllRequest inValue = new GoPlay.Web.MineManiaService.V2SyncAllRequest();
            inValue.info = info;
            GoPlay.Web.MineManiaService.V2SyncAllResponse retVal = ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).V2SyncAll(inValue);
            return retVal.SyncAll;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2SyncAllResponse> GoPlay.Web.MineManiaService.MMWSSoap.V2SyncAllAsync(GoPlay.Web.MineManiaService.V2SyncAllRequest request) {
            return base.Channel.V2SyncAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2SyncAllResponse> V2SyncAllAsync(GoPlay.Web.MineManiaService.SyncInfoV2 info) {
            GoPlay.Web.MineManiaService.V2SyncAllRequest inValue = new GoPlay.Web.MineManiaService.V2SyncAllRequest();
            inValue.info = info;
            return ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).V2SyncAllAsync(inValue);
        }
        
        public GoPlay.Web.MineManiaService.Score[] V2GetRankings(string[] sFriendIds, int nMyUserId, int nLevel) {
            return base.Channel.V2GetRankings(sFriendIds, nMyUserId, nLevel);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.Score[]> V2GetRankingsAsync(string[] sFriendIds, int nMyUserId, int nLevel) {
            return base.Channel.V2GetRankingsAsync(sFriendIds, nMyUserId, nLevel);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoPlay.Web.MineManiaService.V2IsNewDayResponse GoPlay.Web.MineManiaService.MMWSSoap.V2IsNewDay(GoPlay.Web.MineManiaService.V2IsNewDayRequest request) {
            return base.Channel.V2IsNewDay(request);
        }
        
        public GoPlay.Web.MineManiaService.UsageResult V2IsNewDay(int nUserId) {
            GoPlay.Web.MineManiaService.V2IsNewDayRequest inValue = new GoPlay.Web.MineManiaService.V2IsNewDayRequest();
            inValue.nUserId = nUserId;
            GoPlay.Web.MineManiaService.V2IsNewDayResponse retVal = ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).V2IsNewDay(inValue);
            return retVal.Usage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2IsNewDayResponse> GoPlay.Web.MineManiaService.MMWSSoap.V2IsNewDayAsync(GoPlay.Web.MineManiaService.V2IsNewDayRequest request) {
            return base.Channel.V2IsNewDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.V2IsNewDayResponse> V2IsNewDayAsync(int nUserId) {
            GoPlay.Web.MineManiaService.V2IsNewDayRequest inValue = new GoPlay.Web.MineManiaService.V2IsNewDayRequest();
            inValue.nUserId = nUserId;
            return ((GoPlay.Web.MineManiaService.MMWSSoap)(this)).V2IsNewDayAsync(inValue);
        }
        
        public GoPlay.Web.MineManiaService.GiftRedemptionInfo V2GetGiftRedemptionInfo(string sMyFBId) {
            return base.Channel.V2GetGiftRedemptionInfo(sMyFBId);
        }
        
        public System.Threading.Tasks.Task<GoPlay.Web.MineManiaService.GiftRedemptionInfo> V2GetGiftRedemptionInfoAsync(string sMyFBId) {
            return base.Channel.V2GetGiftRedemptionInfoAsync(sMyFBId);
        }
        
        public void V2SetGiftRedemptionInfo(string sMyFBId, int nRedeemCount) {
            base.Channel.V2SetGiftRedemptionInfo(sMyFBId, nRedeemCount);
        }
        
        public System.Threading.Tasks.Task V2SetGiftRedemptionInfoAsync(string sMyFBId, int nRedeemCount) {
            return base.Channel.V2SetGiftRedemptionInfoAsync(sMyFBId, nRedeemCount);
        }
        
        public string[] V2GetTicketInfo(string sMyFBId, int nLevel) {
            return base.Channel.V2GetTicketInfo(sMyFBId, nLevel);
        }
        
        public System.Threading.Tasks.Task<string[]> V2GetTicketInfoAsync(string sMyFBId, int nLevel) {
            return base.Channel.V2GetTicketInfoAsync(sMyFBId, nLevel);
        }
        
        public int V2AddTicketInfo(string sMyFBId, int nLevel, string[] FbIds) {
            return base.Channel.V2AddTicketInfo(sMyFBId, nLevel, FbIds);
        }
        
        public System.Threading.Tasks.Task<int> V2AddTicketInfoAsync(string sMyFBId, int nLevel, string[] FbIds) {
            return base.Channel.V2AddTicketInfoAsync(sMyFBId, nLevel, FbIds);
        }
        
        public bool V2UnlockLevel(int nUserId, int nLevel) {
            return base.Channel.V2UnlockLevel(nUserId, nLevel);
        }
        
        public System.Threading.Tasks.Task<bool> V2UnlockLevelAsync(int nUserId, int nLevel) {
            return base.Channel.V2UnlockLevelAsync(nUserId, nLevel);
        }
    }
}
