//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a member?.
        /// </summary>
        public static string Already_a_member {
            get {
                return ResourceManager.GetString("Already_a_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call our support agent and get your answer immediately..
        /// </summary>
        public static string Call_our_support_agent {
            get {
                return ResourceManager.GetString("Call_our_support_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        public static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string Coming_Soon {
            get {
                return ResourceManager.GetString("Coming_Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Rating.
        /// </summary>
        public static string Content_Rating {
            get {
                return ResourceManager.GetString("Content_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string Current_Version {
            get {
                return ResourceManager.GetString("Current_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover fun, unique and innovative games from up-and-coming developers!.
        /// </summary>
        public static string Discover_fun_unique {
            get {
                return ResourceManager.GetString("Discover_fun_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string Dont_have_an_account {
            get {
                return ResourceManager.GetString("Dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password ?.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get special deals, best price for in-game items and exclusive content only available to our GToken members..
        /// </summary>
        public static string Get_special_deals_best_price {
            get {
                return ResourceManager.GetString("Get_special_deals_best_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s transferable.
        /// </summary>
        public static string It_transferable {
            get {
                return ResourceManager.GetString("It_transferable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Log_Out {
            get {
                return ResourceManager.GetString("Log_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and having fun!.
        /// </summary>
        public static string Login_and_having_fun {
            get {
                return ResourceManager.GetString("Login_and_having_fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our customer support team are happy to answer your questions.
        /// </summary>
        public static string Our_customer_support_team {
            get {
                return ResourceManager.GetString("Our_customer_support_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your account now to get free Play Token and start playing today!.
        /// </summary>
        public static string Register_your_account_now {
            get {
                return ResourceManager.GetString("Register_your_account_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string Release_Date {
            get {
                return ResourceManager.GetString("Release_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retype email.
        /// </summary>
        public static string retype_email {
            get {
                return ResourceManager.GetString("retype_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Less.
        /// </summary>
        public static string See_Less {
            get {
                return ResourceManager.GetString("See_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string See_More {
            get {
                return ResourceManager.GetString("See_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Us A Message.
        /// </summary>
        public static string Send_Us_A_Message {
            get {
                return ResourceManager.GetString("Send_Us_A_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send your message.
        /// </summary>
        public static string Send_your_message {
            get {
                return ResourceManager.GetString("Send_your_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply because....
        /// </summary>
        public static string Simply_because {
            get {
                return ResourceManager.GetString("Simply_because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay supported.
        /// </summary>
        public static string Stay_supported {
            get {
                return ResourceManager.GetString("Stay_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string Terms_of_Service {
            get {
                return ResourceManager.GetString("Terms_of_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Username and/or password are not correct.
        /// </summary>
        public static string Username_and_or_password_are_not_correct {
            get {
                return ResourceManager.GetString("Username_and_or_password_are_not_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope to bring happiness and share the joy with you.
        /// </summary>
        public static string We_hope_to_bring_happiness {
            get {
                return ResourceManager.GetString("We_hope_to_bring_happiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide our undivided attention and support to our users who requires help and attention, be it regarding a technical issue, advice on how to clear a stage you are stuck with, or even a gaming companion when you wish to find someone you can play with..
        /// </summary>
        public static string We_provide_our_undivided_attention {
            get {
                return ResourceManager.GetString("We_provide_our_undivided_attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We seek out popular and quality games to introduce to our users. We reward our users who achieve VIP status with loyalty rewards, which can be used to redeem exclusive and limited edition items for the games you play..
        /// </summary>
        public static string We_seek_out_popular_and_quality {
            get {
                return ResourceManager.GetString("We_seek_out_popular_and_quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s On Your Mind.
        /// </summary>
        public static string What_On_Your_Mind {
            get {
                return ResourceManager.GetString("What_On_Your_Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why choose GToken ?.
        /// </summary>
        public static string Why_choose_GToken {
            get {
                return ResourceManager.GetString("Why_choose_GToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your device model.
        /// </summary>
        public static string Your_device_model {
            get {
                return ResourceManager.GetString("Your_device_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string Your_email {
            get {
                return ResourceManager.GetString("Your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your message.
        /// </summary>
        public static string Your_message {
            get {
                return ResourceManager.GetString("Your_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string Your_name {
            get {
                return ResourceManager.GetString("Your_name", resourceCulture);
            }
        }
    }
}
