//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class active_gamer_scheme
    {
        public int customer_account_id { get; set; }
        public int inviter_id { get; set; }
        public Nullable<decimal> balance { get; set; }
        public bool is_archived { get; set; }
        public string reward { get; set; }
    
        public virtual customer_account customer_account { get; set; }
        public virtual customer_account customer_account1 { get; set; }
    }
}
