//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_log
    {
        public int id { get; set; }
        public string action { get; set; }
        public string version { get; set; }
        public string ip_address { get; set; }
        public Nullable<int> game_id { get; set; }
        public string data { get; set; }
        public string message { get; set; }
        public System.DateTime created_at { get; set; }
        public bool status { get; set; }
        public string user_agent { get; set; }
        public string country_code { get; set; }
        public Nullable<int> customer_account_id { get; set; }
    
        public virtual customer_account customer_account { get; set; }
        public virtual game game { get; set; }
    }
}
