//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_action
    {
        public auth_action()
        {
            this.auth_role = new HashSet<auth_role>();
        }
    
        public int id { get; set; }
        public string action { get; set; }
    
        public virtual ICollection<auth_role> auth_role { get; set; }
    }
}
