//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_role
    {
        public auth_role()
        {
            this.customer_account = new HashSet<customer_account>();
            this.auth_action = new HashSet<auth_action>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<customer_account> customer_account { get; set; }
        public virtual ICollection<auth_action> auth_action { get; set; }
    }
}
