//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class coin_transaction
    {
        public coin_transaction()
        {
            this.credit_transaction = new HashSet<credit_transaction>();
        }
    
        public int id { get; set; }
        public int customer_account_id { get; set; }
        public Nullable<int> receiver_account_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> partner_account_id { get; set; }
        public Nullable<int> game_id { get; set; }
        public Nullable<int> credit_type_id { get; set; }
        public Nullable<int> package_id { get; set; }
        public System.DateTime created_at { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public Nullable<int> topup_card_id { get; set; }
        public string order_id { get; set; }
        public string payment_method { get; set; }
        public Nullable<int> sender_account_id { get; set; }
        public Nullable<int> gtoken_package_id { get; set; }
        public string paypal_redirect_urls { get; set; }
        public string paypal_payment_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string ip_address { get; set; }
        public string country_code { get; set; }
        public string telkom_order_id { get; set; }
        public bool use_gtoken { get; set; }
    
        public virtual credit_type credit_type { get; set; }
        public virtual customer_account customer_account { get; set; }
        public virtual game game { get; set; }
        public virtual gtoken_package gtoken_package { get; set; }
        public virtual package package { get; set; }
        public virtual partner_account partner_account { get; set; }
        public virtual customer_account customer_account1 { get; set; }
        public virtual customer_account customer_account2 { get; set; }
        public virtual topup_card topup_card { get; set; }
        public virtual ICollection<credit_transaction> credit_transaction { get; set; }
    }
}
