//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_transaction
    {
        public int id { get; set; }
        public int customer_account_id { get; set; }
        public Nullable<int> coin_transaction_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> game_id { get; set; }
        public Nullable<int> credit_type_id { get; set; }
        public Nullable<int> package_id { get; set; }
        public System.DateTime created_at { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public Nullable<int> free_coin_transaction_id { get; set; }
    
        public virtual coin_transaction coin_transaction { get; set; }
        public virtual credit_type credit_type { get; set; }
        public virtual customer_account customer_account { get; set; }
        public virtual free_coin_transaction free_coin_transaction { get; set; }
        public virtual game game { get; set; }
        public virtual package package { get; set; }
    }
}
