//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_account
    {
        public customer_account()
        {
            this.active_gamer_scheme1 = new HashSet<active_gamer_scheme>();
            this.api_log = new HashSet<api_log>();
            this.coin_transaction = new HashSet<coin_transaction>();
            this.coin_transaction1 = new HashSet<coin_transaction>();
            this.coin_transaction2 = new HashSet<coin_transaction>();
            this.credit_balance = new HashSet<credit_balance>();
            this.credit_transaction = new HashSet<credit_transaction>();
            this.customer_login_oauth = new HashSet<customer_login_oauth>();
            this.customer_login_password = new HashSet<customer_login_password>();
            this.external_exchange = new HashSet<external_exchange>();
            this.free_coin_transaction = new HashSet<free_coin_transaction>();
            this.friends = new HashSet<friend>();
            this.friends1 = new HashSet<friend>();
            this.game_access_token = new HashSet<game_access_token>();
            this.gcoin_transaction = new HashSet<gcoin_transaction>();
            this.topup_card = new HashSet<topup_card>();
            this.user_notification = new HashSet<user_notification>();
            this.auth_role = new HashSet<auth_role>();
            this.studios = new HashSet<studio>();
        }
    
        public int id { get; set; }
        public string nickname { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string avatar_filename { get; set; }
        public string vip { get; set; }
        public Nullable<decimal> play_token { get; set; }
        public Nullable<int> inviter_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime last_login_at { get; set; }
        public bool is_archived { get; set; }
        public string referral_code { get; set; }
        public Nullable<int> password_credential_id { get; set; }
        public Nullable<decimal> free_play_token { get; set; }
        public string bio { get; set; }
        public string locale { get; set; }
        public string country_code { get; set; }
        public string country_name { get; set; }
        public Nullable<int> game_id { get; set; }
        public string cover_filename { get; set; }
        public string account_manager { get; set; }
        public string account_manager_note { get; set; }
        public Nullable<decimal> gcoin { get; set; }
        public bool is_discount_permanent { get; set; }
        public Nullable<System.DateTime> referred_at { get; set; }
    
        public virtual active_gamer_scheme active_gamer_scheme { get; set; }
        public virtual ICollection<active_gamer_scheme> active_gamer_scheme1 { get; set; }
        public virtual ICollection<api_log> api_log { get; set; }
        public virtual ICollection<coin_transaction> coin_transaction { get; set; }
        public virtual ICollection<coin_transaction> coin_transaction1 { get; set; }
        public virtual ICollection<coin_transaction> coin_transaction2 { get; set; }
        public virtual ICollection<credit_balance> credit_balance { get; set; }
        public virtual ICollection<credit_transaction> credit_transaction { get; set; }
        public virtual game game { get; set; }
        public virtual ICollection<customer_login_oauth> customer_login_oauth { get; set; }
        public virtual ICollection<customer_login_password> customer_login_password { get; set; }
        public virtual ICollection<external_exchange> external_exchange { get; set; }
        public virtual ICollection<free_coin_transaction> free_coin_transaction { get; set; }
        public virtual ICollection<friend> friends { get; set; }
        public virtual ICollection<friend> friends1 { get; set; }
        public virtual ICollection<game_access_token> game_access_token { get; set; }
        public virtual ICollection<gcoin_transaction> gcoin_transaction { get; set; }
        public virtual ICollection<topup_card> topup_card { get; set; }
        public virtual ICollection<user_notification> user_notification { get; set; }
        public virtual ICollection<auth_role> auth_role { get; set; }
        public virtual ICollection<studio> studios { get; set; }
    }
}
