//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class external_exchange
    {
        public int id { get; set; }
        public int customer_account_id { get; set; }
        public int game_id { get; set; }
        public Nullable<int> package_id { get; set; }
        public Nullable<int> credit_type_id { get; set; }
        public string exchange_option_identifier { get; set; }
        public System.DateTime created_at { get; set; }
        public string transaction_id { get; set; }
    
        public virtual credit_type credit_type { get; set; }
        public virtual customer_account customer_account { get; set; }
        public virtual game game { get; set; }
        public virtual package package { get; set; }
    }
}
