//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_notification
    {
        public game_notification()
        {
            this.user_notification = new HashSet<user_notification>();
        }
    
        public int id { get; set; }
        public int game_id { get; set; }
        public Nullable<int> good_id { get; set; }
        public Nullable<int> good_amount { get; set; }
        public Nullable<int> good_type { get; set; }
        public string description { get; set; }
    
        public virtual game game { get; set; }
        public virtual ICollection<user_notification> user_notification { get; set; }
    }
}
