//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public game()
        {
            this.api_log = new HashSet<api_log>();
            this.coin_transaction = new HashSet<coin_transaction>();
            this.credit_transaction = new HashSet<credit_transaction>();
            this.credit_type = new HashSet<credit_type>();
            this.customer_account = new HashSet<customer_account>();
            this.external_exchange = new HashSet<external_exchange>();
            this.free_coin_transaction = new HashSet<free_coin_transaction>();
            this.game_access_token = new HashSet<game_access_token>();
            this.game_notification = new HashSet<game_notification>();
            this.gcoin_transaction = new HashSet<gcoin_transaction>();
            this.packages = new HashSet<package>();
        }
    
        public int id { get; set; }
        public string guid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public bool is_archived { get; set; }
        public Nullable<int> studio_id { get; set; }
        public bool is_active { get; set; }
        public string banner_filename { get; set; }
        public string icon_filename { get; set; }
        public string download_links { get; set; }
        public string thumb_filename { get; set; }
        public string genre { get; set; }
        public string short_description { get; set; }
        public string endpoint { get; set; }
        public string gtoken_client_id { get; set; }
        public string gtoken_client_secret { get; set; }
        public string slider_images { get; set; }
        public string current_version { get; set; }
        public string file_size { get; set; }
        public string content_rating { get; set; }
        public string current_changelog { get; set; }
        public Nullable<System.DateTime> released_at { get; set; }
    
        public virtual ICollection<api_log> api_log { get; set; }
        public virtual ICollection<coin_transaction> coin_transaction { get; set; }
        public virtual ICollection<credit_transaction> credit_transaction { get; set; }
        public virtual ICollection<credit_type> credit_type { get; set; }
        public virtual ICollection<customer_account> customer_account { get; set; }
        public virtual ICollection<external_exchange> external_exchange { get; set; }
        public virtual ICollection<free_coin_transaction> free_coin_transaction { get; set; }
        public virtual ICollection<game_access_token> game_access_token { get; set; }
        public virtual ICollection<game_notification> game_notification { get; set; }
        public virtual studio studio { get; set; }
        public virtual ICollection<gcoin_transaction> gcoin_transaction { get; set; }
        public virtual ICollection<package> packages { get; set; }
    }
}
