//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class gcoin_transaction
    {
        public int id { get; set; }
        public int customer_account_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> game_id { get; set; }
        public string description { get; set; }
        public System.DateTime created_at { get; set; }
        public string order_id { get; set; }
        public string status { get; set; }
        public string ip_address { get; set; }
        public string country_code { get; set; }
        public string payment_method { get; set; }
        public string sender_email { get; set; }
        public string receiver_email { get; set; }
        public string pay_key { get; set; }
        public Nullable<System.DateTime> pay_key_expiration_date { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual customer_account customer_account { get; set; }
        public virtual game game { get; set; }
    }
}
