//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class gtoken_package
    {
        public gtoken_package()
        {
            this.coin_transaction = new HashSet<coin_transaction>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string icon_filename { get; set; }
        public Nullable<decimal> play_token_amount { get; set; }
        public string sku { get; set; }
        public string currency { get; set; }
        public string icon_animation_html { get; set; }
        public bool is_archived { get; set; }
    
        public virtual ICollection<coin_transaction> coin_transaction { get; set; }
    }
}
