//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EF : DbContext
    {
        public EF()
            : base("name=EF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<active_gamer_scheme> active_gamer_scheme { get; set; }
        public virtual DbSet<admin_account> admin_account { get; set; }
        public virtual DbSet<api_log> api_log { get; set; }
        public virtual DbSet<auth_action> auth_action { get; set; }
        public virtual DbSet<auth_role> auth_role { get; set; }
        public virtual DbSet<coin_transaction> coin_transaction { get; set; }
        public virtual DbSet<credit_balance> credit_balance { get; set; }
        public virtual DbSet<credit_transaction> credit_transaction { get; set; }
        public virtual DbSet<credit_type> credit_type { get; set; }
        public virtual DbSet<customer_account> customer_account { get; set; }
        public virtual DbSet<customer_login_oauth> customer_login_oauth { get; set; }
        public virtual DbSet<customer_login_password> customer_login_password { get; set; }
        public virtual DbSet<external_exchange> external_exchange { get; set; }
        public virtual DbSet<free_coin_transaction> free_coin_transaction { get; set; }
        public virtual DbSet<friend> friends { get; set; }
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<game_access_token> game_access_token { get; set; }
        public virtual DbSet<game_notification> game_notification { get; set; }
        public virtual DbSet<gcoin_transaction> gcoin_transaction { get; set; }
        public virtual DbSet<gtoken_package> gtoken_package { get; set; }
        public virtual DbSet<oauth_client> oauth_client { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<partner_account> partner_account { get; set; }
        public virtual DbSet<paypal_preapproval> paypal_preapproval { get; set; }
        public virtual DbSet<studio> studios { get; set; }
        public virtual DbSet<topup_card> topup_card { get; set; }
        public virtual DbSet<user_notification> user_notification { get; set; }
        public virtual DbSet<venvici_transaction> venvici_transaction { get; set; }
        public virtual DbSet<schemup_tables> schemup_tables { get; set; }
    }
}
