//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class oauth_client
    {
        public int id { get; set; }
        public string name { get; set; }
        public string client_id { get; set; }
        public string client_secret { get; set; }
        public string client_type { get; set; }
        public string C_redirect_uris { get; set; }
        public string C_default_scopes { get; set; }
    }
}
