//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        public package()
        {
            this.coin_transaction = new HashSet<coin_transaction>();
            this.credit_transaction = new HashSet<credit_transaction>();
            this.external_exchange = new HashSet<external_exchange>();
            this.free_coin_transaction = new HashSet<free_coin_transaction>();
        }
    
        public int id { get; set; }
        public int game_id { get; set; }
        public string name { get; set; }
        public decimal play_token_value { get; set; }
        public string icon_filename { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public bool is_archived { get; set; }
        public Nullable<int> old_db_id { get; set; }
        public Nullable<decimal> free_play_token_value { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string string_identifier { get; set; }
        public Nullable<int> limited_time_offer { get; set; }
    
        public virtual ICollection<coin_transaction> coin_transaction { get; set; }
        public virtual ICollection<credit_transaction> credit_transaction { get; set; }
        public virtual ICollection<external_exchange> external_exchange { get; set; }
        public virtual ICollection<free_coin_transaction> free_coin_transaction { get; set; }
        public virtual game game { get; set; }
    }
}
