//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_notification
    {
        public int id { get; set; }
        public int customer_account_id { get; set; }
        public Nullable<int> game_notification_id { get; set; }
        public System.DateTime created_at { get; set; }
        public bool is_archived { get; set; }
    
        public virtual customer_account customer_account { get; set; }
        public virtual game_notification game_notification { get; set; }
    }
}
