//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Dal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class venvici_transaction
    {
        public int id { get; set; }
        public string order_id { get; set; }
        public string username { get; set; }
        public Nullable<decimal> gtoken_deduct_amount { get; set; }
        public Nullable<decimal> commission_credit_amount { get; set; }
        public Nullable<decimal> pushbv_amount { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
