//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string _for {
            get {
                return ResourceManager.GetString("_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A better way.
        /// </summary>
        public static string A_better_way {
            get {
                return ResourceManager.GetString("A_better_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Gateway to Play.
        /// </summary>
        public static string A_Gateway_to_Play {
            get {
                return ResourceManager.GetString("A_Gateway_to_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lifestyle platform, GToken caters to various aspects of one’s life. Ranging from play to relaxation, GToken provides members with choices that one cannot resist..
        /// </summary>
        public static string A_lifestyle_platform {
            get {
                return ResourceManager.GetString("A_lifestyle_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lifestyle platform, GToken caters to various aspects of one’s life. Ranging from play to relaxation, GToken provides members with choices that one cannot resist..
        /// </summary>
        public static string About_page_A_lifestyle_platform {
            get {
                return ResourceManager.GetString("About_page_A_lifestyle_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alongside the vision to serve the community, GToken opens up its first-ever F&amp;B venture on Dempsey Hill. G House Restaurant offers a comprehensive and savoury menu for all to enjoy. G House Restaurant serves a delectable All-Day Breakfast, a savoury Asian Fusion and a range of healthy selections under Eat Clean. Such a variety encourages people of all, regardless whether a family, a group of friends or a couple to enjoy a meal in an environment rich with history.
        /// </summary>
        public static string About_page_Alongside_the_vision {
            get {
                return ResourceManager.GetString("About_page_Alongside_the_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine - GDine.co.
        /// </summary>
        public static string About_page_Dine_GDine {
            get {
                return ResourceManager.GetString("About_page_Dine_GDine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food is a necessity in life that everyone enjoys. GDine.co offers various dining options under one roof. Being part of our lifestyles, food and dining becomes essentially a choice one makes. GDine.co brings merchants that values consumers’ loyalty and wants to share more value constantly. Members enjoys exclusive discounts from participating merchants 365 days, a year. Spend lesser, enjoy more!.
        /// </summary>
        public static string About_page_Food_is_a_necessity {
            get {
                return ResourceManager.GetString("About_page_Food_is_a_necessity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games - GoPlay.la.
        /// </summary>
        public static string About_page_Games_GoPlay {
            get {
                return ResourceManager.GetString("About_page_Games_GoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoPlay.la provides gamers and members the chance to play and reach out to high quality games which are admist the millions of applications on mobile stores. GoPlay.la provides a 24/7 online customer service support, where technical issues and game stuck will be assisted. GoPlay.la provides a safe and friendly community in reality and not just virtually; with a GToken Clubhouse in Singapore and Malaysia, it is readily available for gamers to gather, build relationships and play! GoPlay.la provides game devel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_page_GoPlay_provides {
            get {
                return ResourceManager.GetString("About_page_GoPlay_provides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is important that everyone reach a balance of work and play. GToken visions that games are a part of a bonding tool, having the ability to breakthrough emotional walls and barriers..
        /// </summary>
        public static string About_page_It_is_important {
            get {
                return ResourceManager.GetString("About_page_It_is_important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string Admin_panel {
            get {
                return ResourceManager.GetString("Admin_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alongside the vision to serve the community, GToken opens up its first-ever F&amp;B venture on Dempsey Hill. G House Restaurant offers a comprehensive and savoury menu for all to enjoy. G House Restaurant serves a delectable All-Day Breakfast, a savoury Asian Fusion and a range of healthy selections under Eat Clean. Such a variety encourages people of all, regardless whether a family, a group of friends or a couple to enjoy a meal in an environment rich with history.
        /// </summary>
        public static string Alongside_the_vision_to_serve_the_community {
            get {
                return ResourceManager.GetString("Alongside_the_vision_to_serve_the_community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a member?.
        /// </summary>
        public static string Already_a_member {
            get {
                return ResourceManager.GetString("Already_a_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a user?.
        /// </summary>
        public static string Already_a_user {
            get {
                return ResourceManager.GetString("Already_a_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available from Mon - Fri, 11am to 7pm..
        /// </summary>
        public static string Available_from_Mon_Fri_11am_to_7pm {
            get {
                return ResourceManager.GetString("Available_from_Mon_Fri_11am_to_7pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWESOME GAMES SUPPORTED.
        /// </summary>
        public static string Awesome_games_supported {
            get {
                return ResourceManager.GetString("Awesome_games_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call our support agent and get your answer immediately..
        /// </summary>
        public static string Call_our_support_agent {
            get {
                return ResourceManager.GetString("Call_our_support_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        public static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string Coming_Soon {
            get {
                return ResourceManager.GetString("Coming_Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Rating.
        /// </summary>
        public static string Content_Rating {
            get {
                return ResourceManager.GetString("Content_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string Current_Version {
            get {
                return ResourceManager.GetString("Current_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Date_of_birth {
            get {
                return ResourceManager.GetString("Date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated staffs to provide assistance. Need technical support or a friend to play with? We are here for you!.
        /// </summary>
        public static string Dedicated_staffs_to_provide_assistance {
            get {
                return ResourceManager.GetString("Dedicated_staffs_to_provide_assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine - GDine.co.
        /// </summary>
        public static string Dine_GDine_co {
            get {
                return ResourceManager.GetString("Dine_GDine_co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover fun, unique and innovative games from up-and-coming developers!.
        /// </summary>
        public static string Discover_fun_unique {
            get {
                return ResourceManager.GetString("Discover_fun_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string Dont_have_an_account {
            get {
                return ResourceManager.GetString("Dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy &amp; simple, no credit card needed.
        /// </summary>
        public static string Easy_simple_no_credit_card {
            get {
                return ResourceManager.GetString("Easy_simple_no_credit_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your profile.
        /// </summary>
        public static string Edit_your_profile {
            get {
                return ResourceManager.GetString("Edit_your_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an electronic receipt..
        /// </summary>
        public static string Electronic_receipt {
            get {
                return ResourceManager.GetString("Electronic_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email_address {
            get {
                return ResourceManager.GetString("Email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string Enter_new_password {
            get {
                return ResourceManager.GetString("Enter_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food is a necessity in life that everyone enjoys. GDine.co offers various dining options under one roof. Being part of our lifestyles, food and dining becomes essentially a choice one makes. GDine.co brings merchants that values consumers’ loyalty and wants to share more value constantly. Members enjoys exclusive discounts from participating merchants 365 days, a year. Spend lesser, enjoy more!.
        /// </summary>
        public static string Food_is_a_necessity {
            get {
                return ResourceManager.GetString("Food_is_a_necessity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot it?.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game version.
        /// </summary>
        public static string Game_version {
            get {
                return ResourceManager.GetString("Game_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games - GoPlay.la.
        /// </summary>
        public static string Games_GoPlay_la {
            get {
                return ResourceManager.GetString("Games_GoPlay_la", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games that GToken distributes.
        /// </summary>
        public static string Games_that_GToken_distributes {
            get {
                return ResourceManager.GetString("Games_that_GToken_distributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Great Discounts.
        /// </summary>
        public static string Get_Great_Discounts {
            get {
                return ResourceManager.GetString("Get_Great_Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GToken members enjoy discounts from merchants on our various platforms. This way, members stand to spend less yet get more. Members are also able to transfer tokens to friends and family as gifts!.
        /// </summary>
        public static string Get_Great_Discounts_description {
            get {
                return ResourceManager.GetString("Get_Great_Discounts_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more with GToken.
        /// </summary>
        public static string Get_more_with_GToken {
            get {
                return ResourceManager.GetString("Get_more_with_GToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get special deals, best price for in-game items and exclusive content only available to our GToken members..
        /// </summary>
        public static string Get_special_deals_best_price {
            get {
                return ResourceManager.GetString("Get_special_deals_best_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoPlay.la provides gamers and members the chance to play and reach out to high quality games which are admist the millions of applications on mobile stores. GoPlay.la provides a 24/7 online customer service support, where technical issues and game stuck will be assisted. GoPlay.la provides a safe and friendly community in reality and not just virtually; with a GToken Clubhouse in Singapore and Malaysia, it is readily available for gamers to gather, build relationships and play! GoPlay.la provides game devel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GoPlay_provides_gamers {
            get {
                return ResourceManager.GetString("GoPlay_provides_gamers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoPlay is a digital currency platform for mobile games that delivers greater choices, convenience and simplicity to our customers in all that we do..
        /// </summary>
        public static string GoPlay_Token_is_a_digital_currency_platform {
            get {
                return ResourceManager.GetString("GoPlay_Token_is_a_digital_currency_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST.
        /// </summary>
        public static string GST {
            get {
                return ResourceManager.GetString("GST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GToken Clubhouses.
        /// </summary>
        public static string GToken_Clubhouses {
            get {
                return ResourceManager.GetString("GToken_Clubhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GToken encourages community building and relationship bonding. Clubhouses are situated around Asia for members to gather, connect and have fun together!.
        /// </summary>
        public static string GToken_Clubhouses_description {
            get {
                return ResourceManager.GetString("GToken_Clubhouses_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GToken is a gateway to play: when you play, you get happiness. We hope to bring happiness and share the joy with your friends and loved ones when you play with us..
        /// </summary>
        public static string GToken_is_a_gateway_to_play {
            get {
                return ResourceManager.GetString("GToken_is_a_gateway_to_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GToken website.
        /// </summary>
        public static string GToken_website {
            get {
                return ResourceManager.GetString("GToken_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How about going back to.
        /// </summary>
        public static string How_about_going_back_to {
            get {
                return ResourceManager.GetString("How_about_going_back_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to GToken&apos;s.
        /// </summary>
        public static string I_agree_to_GToken {
            get {
                return ResourceManager.GetString("I_agree_to_GToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing GToken.
        /// </summary>
        public static string Introducing_GToken {
            get {
                return ResourceManager.GetString("Introducing_GToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is important that everyone reach a balance of work and play. GToken visions that games are a part of a bonding tool, having the ability to breakthrough emotional walls and barriers..
        /// </summary>
        public static string It_is_important_that_everyone_reach {
            get {
                return ResourceManager.GetString("It_is_important_that_everyone_reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s transferable.
        /// </summary>
        public static string It_transferable {
            get {
                return ResourceManager.GetString("It_transferable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Log_Out {
            get {
                return ResourceManager.GetString("Log_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and having fun!.
        /// </summary>
        public static string Login_and_having_fun {
            get {
                return ResourceManager.GetString("Login_and_having_fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login now.
        /// </summary>
        public static string Login_now {
            get {
                return ResourceManager.GetString("Login_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string My_Account {
            get {
                return ResourceManager.GetString("My_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string My_profile {
            get {
                return ResourceManager.GetString("My_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nah, don&apos;t change password.
        /// </summary>
        public static string Nah_dont_change_password {
            get {
                return ResourceManager.GetString("Nah_dont_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Immediate Help ?.
        /// </summary>
        public static string Need_Immediate_Help {
            get {
                return ResourceManager.GetString("Need_Immediate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name.
        /// </summary>
        public static string Nick_name {
            get {
                return ResourceManager.GetString("Nick_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No receipt available for you!.
        /// </summary>
        public static string No_receipt_available_for_you {
            get {
                return ResourceManager.GetString("No_receipt_available_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a user?.
        /// </summary>
        public static string Not_a_user {
            get {
                return ResourceManager.GetString("Not_a_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Login To All.
        /// </summary>
        public static string One_Login_To_All {
            get {
                return ResourceManager.GetString("One_Login_To_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving time and gaining convenience, members of GToken only require 1 unique userid and 1 password to access all accounts on our platform..
        /// </summary>
        public static string One_Login_To_All_description {
            get {
                return ResourceManager.GetString("One_Login_To_All_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS version.
        /// </summary>
        public static string OS_version {
            get {
                return ResourceManager.GetString("OS_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Recommendations.
        /// </summary>
        public static string Other_Recommendations {
            get {
                return ResourceManager.GetString("Other_Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our customer support team are happy to answer your questions.
        /// </summary>
        public static string Our_customer_support_team {
            get {
                return ResourceManager.GetString("Our_customer_support_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found!.
        /// </summary>
        public static string Page_not_found {
            get {
                return ResourceManager.GetString("Page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Call.
        /// </summary>
        public static string Phone_Call {
            get {
                return ResourceManager.GetString("Phone_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please kindly contact.
        /// </summary>
        public static string Please_kindly_contact_part1 {
            get {
                return ResourceManager.GetString("Please_kindly_contact_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you have any questions or concerns. Please be sure to forward this invoice as well to expedite processing of your request..
        /// </summary>
        public static string Please_kindly_contact_part2 {
            get {
                return ResourceManager.GetString("Please_kindly_contact_part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later..
        /// </summary>
        public static string Please_try_again_later {
            get {
                return ResourceManager.GetString("Please_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really sorry, our system is down due to a problem..
        /// </summary>
        public static string Really_sorry_system_problem {
            get {
                return ResourceManager.GetString("Really_sorry_system_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referal ID.
        /// </summary>
        public static string Referal_ID {
            get {
                return ResourceManager.GetString("Referal_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your account now to get free Play Token and start playing today!.
        /// </summary>
        public static string Register_your_account_now {
            get {
                return ResourceManager.GetString("Register_your_account_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string Release_Date {
            get {
                return ResourceManager.GetString("Release_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string Reset_your_password {
            get {
                return ResourceManager.GetString("Reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retype email.
        /// </summary>
        public static string retype_email {
            get {
                return ResourceManager.GetString("retype_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        public static string Retype_password {
            get {
                return ResourceManager.GetString("Retype_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Less.
        /// </summary>
        public static string See_Less {
            get {
                return ResourceManager.GetString("See_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string See_More {
            get {
                return ResourceManager.GetString("See_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Us A Message.
        /// </summary>
        public static string Send_Us_A_Message {
            get {
                return ResourceManager.GetString("Send_Us_A_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send your message.
        /// </summary>
        public static string Send_your_message {
            get {
                return ResourceManager.GetString("Send_your_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Charge.
        /// </summary>
        public static string Service_Charge {
            get {
                return ResourceManager.GetString("Service_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share GoPlay Token with your friends and loved ones, and empower them with the freedom to upgrade whichever games they like to play ♥.
        /// </summary>
        public static string Share_GoPlay_Token_with_your_friends {
            get {
                return ResourceManager.GetString("Share_GoPlay_Token_with_your_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up &amp; get 1 free.
        /// </summary>
        public static string Sign_up_get_1_free {
            get {
                return ResourceManager.GetString("Sign_up_get_1_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up &amp; get a free.
        /// </summary>
        public static string Sign_up_get_a_free {
            get {
                return ResourceManager.GetString("Sign_up_get_a_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up here.
        /// </summary>
        public static string Sign_up_here {
            get {
                return ResourceManager.GetString("Sign_up_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup now.
        /// </summary>
        public static string Signup_now {
            get {
                return ResourceManager.GetString("Signup_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply because....
        /// </summary>
        public static string Simply_because {
            get {
                return ResourceManager.GetString("Simply_because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong!.
        /// </summary>
        public static string Something_is_wrong {
            get {
                return ResourceManager.GetString("Something_is_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the page you are looking for is not found.
        /// </summary>
        public static string Sorry_not_found {
            get {
                return ResourceManager.GetString("Sorry_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay supported.
        /// </summary>
        public static string Stay_supported {
            get {
                return ResourceManager.GetString("Stay_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string Terms_of_Service {
            get {
                return ResourceManager.GetString("Terms_of_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your business!.
        /// </summary>
        public static string Thank_you {
            get {
                return ResourceManager.GetString("Thank_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to enhance your gaming experience.
        /// </summary>
        public static string to_enhance_your_gaming_experience {
            get {
                return ResourceManager.GetString("to_enhance_your_gaming_experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        public static string Transaction_History {
            get {
                return ResourceManager.GetString("Transaction_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string Transaction_ID {
            get {
                return ResourceManager.GetString("Transaction_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new photo.
        /// </summary>
        public static string Upload_new_photo {
            get {
                return ResourceManager.GetString("Upload_new_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Username and/or password are not correct.
        /// </summary>
        public static string Username_and_or_password_are_not_correct {
            get {
                return ResourceManager.GetString("Username_and_or_password_are_not_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope to bring happiness and share the joy with you.
        /// </summary>
        public static string We_hope_to_bring_happiness {
            get {
                return ResourceManager.GetString("We_hope_to_bring_happiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide our undivided attention and support to our users who requires help and attention, be it regarding a technical issue, advice on how to clear a stage you are stuck with, or even a gaming companion when you wish to find someone you can play with..
        /// </summary>
        public static string We_provide_our_undivided_attention {
            get {
                return ResourceManager.GetString("We_provide_our_undivided_attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We seek out popular and quality games to introduce to our users. We reward our users who achieve VIP status with loyalty rewards, which can be used to redeem exclusive and limited edition items for the games you play..
        /// </summary>
        public static string We_seek_out_popular_and_quality {
            get {
                return ResourceManager.GetString("We_seek_out_popular_and_quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will get back to you shortly..
        /// </summary>
        public static string We_will_get_back_to_you_shortly {
            get {
                return ResourceManager.GetString("We_will_get_back_to_you_shortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s On Your Mind.
        /// </summary>
        public static string What_On_Your_Mind {
            get {
                return ResourceManager.GetString("What_On_Your_Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT&apos;S YOUR ISSUE ABOUT ?.
        /// </summary>
        public static string WHAT_YOUR_ISSUE_ABOUT {
            get {
                return ResourceManager.GetString("WHAT_YOUR_ISSUE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHICH GAME TROUBLES YOU ?.
        /// </summary>
        public static string WHICH_GAME_TROUBLES_YOU {
            get {
                return ResourceManager.GetString("WHICH_GAME_TROUBLES_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why choose GToken ?.
        /// </summary>
        public static string Why_choose_GToken {
            get {
                return ResourceManager.GetString("Why_choose_GToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR CURRENT OS ?.
        /// </summary>
        public static string YOUR_CURRENT_OS {
            get {
                return ResourceManager.GetString("YOUR_CURRENT_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your device model.
        /// </summary>
        public static string Your_device_model {
            get {
                return ResourceManager.GetString("Your_device_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string Your_email {
            get {
                return ResourceManager.GetString("Your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your message.
        /// </summary>
        public static string Your_message {
            get {
                return ResourceManager.GetString("Your_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string Your_name {
            get {
                return ResourceManager.GetString("Your_name", resourceCulture);
            }
        }
    }
}
